# Generated by Django 5.0.1 on 2024-02-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoudysSlice', '0002_pizza_jalapeños_pizza_pesto_pizza_sausages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='jalapeños',
            new_name='Jalapeños',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pesto',
            new_name='Pesto',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='sausages',
            new_name='Sausages',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='spicychicken',
            new_name='Spicychicken',
        ),
    ]
